theme: jekyll-theme-hacker

# basic options, I can say whatever
Title: Allen is cool
Author: DirtyBooty
Email: allenlu1996@gmail.com
Description: please don’t spam me
Twitter_username: allen
GitHub_username: dirtybooty

# Build settings
Markdown: kramdown
Theme:hacker
